#!/bin/bash

INPUT_FILE=$1

# find text between menuentry and closing curly bracket, first entry
# https://unix.stackexchange.com/questions/180663/how-to-select-first-occurrence-between-two-patterns-including-them
# muru's answer
menuentry=$(sed -n '/^menuentry/, /}/ {p; /}/q}' $INPUT_FILE)

# split by single quotes
menuname=$(echo "$menuentry" | awk -F \' '{print $2}')

# grep keys:
#           -P - perl regex
#           -o - only matched showed
# So, we find line with "linuxefi", splitting it with multiple delimeters (shown in square brackets)
label=$(echo "$menuentry" | grep -Po 'linuxefi.+' | awk -F '[:= ]' '{print $6}')

# change menuentry name between single quotes (add Kickstart in the end)
# after that, take line with linuxefi and append after a space label with some text
# awk keys:
#          -P - compatibility mode. \x sequences are not recognized (needed for exact label)
#          -v - make a variable
result=$(echo "$menuentry" | sed "/^menuentry/s/'[^']*'/'$menuname Kickstart'/" | awk -P -v "var=$label" '/linuxefi/{$0 = $0 (" ") "inst.ks=hd:LABEL="var":/ks.cfg"} 1')
#echo "$result"

