#!/bin/bash

VERSION="7.3.1"

# Падаем при ошибке
set -eo pipefail

# --- for anaconda rpm rebuild ---
# glib2-doc gtk3-devel-docs libarchive-devel libgnomekbd-devel
# libtimezonemap-devel libxklavier-devel audit-libs-devel metacity gtk-doc

# Цветной вывод. Использование: echo -e "${COLOR} some text ${NC}"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\e[0m'

DIRNAME=$(dirname `readlink -e "$0"`)

if [[ "$VERSION" == "7.3.1" ]]; then
        ANACONDA_RPM="src/rpms/base/anaconda/$VERSION/anaconda-33.25.4-6.4.el7.src.rpm"
        ANACONDA_SPEC="src/rpms/base/anaconda/$VERSION/anaconda.spec"
        ANACONDA_PATCH="src/rpms/base/anaconda/$VERSION/0006-user-glade.patch"
elif [[ "$VERSION" == "7.3.2" ]]; then
        ANACONDA_RPM="src/rpms/base/anaconda/$VERSION/anaconda-33.25.4-6.5.el7.src.rpm"
        ANACONDA_SPEC="src/rpms/base/anaconda/$VERSION/anaconda.spec"
        ANACONDA_PATCH="src/rpms/base/anaconda/$VERSION/0006-user-glade.patch"
else
        echo "Wrong version variable"
        exit
fi



INITIAL_RPM="src/rpms/base/initial/initial-setup-0.3.84-3.el7.src.rpm"
INITIAL_SPEC="src/rpms/base/initial/initial-setup.spec"
INITIAL_PATCH="src/rpms/base/initial/0003-common-and-user.patch"

# Не надо запускать сборку RPM под root'ом
if ! [ "$EUID" -ne 0 ] ; then
    echo -e "${RED}Do not run this script as root${NC}"
    exit
fi

# Проверим наличие файлов для сборки
if [[ ! -f "$DIRNAME/$ANACONDA_RPM" || ! -f "$DIRNAME/$ANACONDA_SPEC" \
    || ! -f "$DIRNAME/$ANACONDA_PATCH" || ! -f "$DIRNAME/$INITIAL_RPM" \
    || ! -f "$DIRNAME/$INITIAL_SPEC"  || ! -f "$DIRNAME/$INITIAL_PATCH" ]] ; then
    echo -e "${RED}Some of necessary config files are absent${NC}"
    exit
fi

################################ Rebuild RPMs #######################################

echo -e "${GREEN}Rebuilding anaconda rpm${NC}"
rpmdev-wipetree
rpm -ihv "$DIRNAME/$ANACONDA_RPM"
cp -v "$DIRNAME/$ANACONDA_SPEC"  "$HOME/rpmbuild/SPECS/"
cp -v "$DIRNAME/$ANACONDA_PATCH" "$HOME/rpmbuild/SOURCES/"
rpmbuild -bb "$HOME/rpmbuild/SPECS/anaconda.spec"
cp -v $HOME/rpmbuild/RPMS/x86_64/anaconda-* $DIRNAME/src/rpms/$VERSION

echo -e "${GREEN}Rebuilding initial-setup rpm${NC}"
rpmdev-wipetree
rpm -ihv "$DIRNAME/$INITIAL_RPM"
cp -v "$DIRNAME/$INITIAL_SPEC"  "$HOME/rpmbuild/SPECS/"
cp -v "$DIRNAME/$INITIAL_PATCH" "$HOME/rpmbuild/SOURCES/"
rpmbuild -bb "$HOME/rpmbuild/SPECS/initial-setup.spec"
cp -v $HOME/rpmbuild/RPMS/x86_64/initial* $DIRNAME/src/rpms/$VERSION
